### ISSUE TITLE
Multiple Problems

### ISSUE THREAD

**Issue by octocat1000** [aws-samples/aws-glue-flatten-nested-json#2]
Not sure if AWS is maintaining this anymore but for anyone finding this and trying to run it, I'll save you a little time getting it to work.

1. The way the lambda policy is written you must use a lower case stack name or else the lambda will not be able to execute a Redshift query
2. The glue job is missing parameter: num_level_to_denormalize.  Add it.
2. There are multiple problems with the glue script
a. Function find_tbl_nested_level: the returned dict has a key that is different from the one that the script expects later.  Add key 'number_nested_levels': lvl
b. In the for loop updating the table names:

This:
            tables_to_join_map[str(next_join_lvl)][child_tbl_name] = {
                'join_to_tbls': [], 'join_col': [], 'has_child': False}
Should be:
            tables_to_join_map[str(child_tbl_join_lvl)][child_tbl_name] = {
                'join_to_tbls': [], 'join_col': [], 'has_child': False}

c. (I'm not 100% on this one but this is what I did)

In the denormalize loop at the end, I commented the second predicate in the if.  I cannot figure out what it was meant to be..:

 if table_with_nested_level['table_nested_level'] <= start_join_level:
            if table_with_nested_level['table_found'] == 1: #and table_to_be_joined_with_level['table_nested_level'] == start_join_level

**Comment by fnapolitano73** [comment]
Thank you for opening the Issue I will review the CloudFormation code and fix it.

The errors in the code should be related to a wrong version of the py script (the correct one is the one in this repo) in the s3 bucket referenced by the cloudformation.

as for point c, I will look at simplify it or clarifying it.

**Comment by fnapolitano73** [comment]
Thanks for letting us know, I have fixed the issue in the CloudFormation and pointed it to the right Glue script. Further more I added a comment in the code hoping to have clarified why the second If was there.
