### ISSUE TITLE
Child tables of Child Table to root missing from final dynamicframes_map

### ISSUE THREAD

**Issue by isaac-dasari** [aws-samples/aws-glue-flatten-nested-json#6]
If a child table to root has more child tables, they're missing in the final dynamic frames map.
Relationalize is spitting them, But we're loosing them in clean_column_names.

As, this function will take only root table as input and it'll recursively pick child tables associated to the root.

Also, why is always root table is set to have child to true, any child table can also have another child table.

Can we make this part more generic to dynamically figure if a table (root or child or anything) has a child or not and then clean the column names.

**Comment by fnapolitano73** [comment]
Thank you for bringing this to our attention, I will review the code. 

The use case you mention, was meant to be implemented so I need to verify why it is not working as expected.

Could you share a sample file or just a sample schema that it is similar to your if there is sensitive information?

**Comment by isaac-dasari** [comment]
{
    "timestamp": 1463698479065,
    "dummydata": {
        "DummyKey": "1234567890",
        "UpdateRegion": "us-west",
        "DummyType": "Letter",
        "DummyKeyValues": [{
                "Value": "1234567890",
                "Source": "Dummys-task",
                "TimeStamp": "2021-01-31T20:04:38.9781619Z"
            }
        ],
        "FileTypes": ["zip", "pdf", "csv"],
        "DummyKey": "126gdf1324-36da-s5172-8c4d-vf43526",
        "DummyClassifications": {
            "Values": {
                "Dummy-task": [{
                        "Pages": ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11"],
                        "Value": "Letter",
                        "Source": "Dummy-task",
                        "TimeStamp": "2021-01-28T21:26:02.4571552Z"
                    }
                ],
                "dummy-classification": [{
                        "Pages": ["0"],
                        "Value": "Other",
                        "Source": "dummy-classification",
                        "TimeStamp": "2021-01-28T19:48:34.7445087Z"
                    }, {
                        "Pages": ["1"],
                        "Value": "Other",
                        "Source": "dummy-classification",
                        "TimeStamp": "2021-01-28T19:48:34.7445087Z"
                    }, {
                        "Pages": ["2"],
                        "Value": "Other",
                        "Source": "dummy-classification",
                        "TimeStamp": "2021-01-28T19:48:34.7445087Z"
                    }, {
                        "Pages": ["3"],
                        "Value": "Other",
                        "Source": "dummy-classification",
                        "TimeStamp": "2021-01-28T19:48:34.7445087Z"
                    }, {
                        "Pages": ["4"],
                        "Value": "Other",
                        "Source": "dummy-classification",
                        "TimeStamp": "2021-01-28T19:48:34.7445087Z"
                    }, {
                        "Pages": ["5"],
                        "Value": "Other",
                        "Source": "dummy-classification",
                        "TimeStamp": "2021-01-28T19:48:34.7445087Z"
                    }, {
                        "Pages": ["6"],
                        "Value": "Other",
                        "Source": "dummy-classification",
                        "TimeStamp": "2021-01-28T19:48:34.7445087Z"
                    }, {
                        "Pages": ["7","8"],
                        "Value": "Other",
                        "Source": "dummy-classification",
                        "TimeStamp": "2021-01-28T19:48:34.7445087Z"
                    }
                ]
            },
            "Overall": [{
                    "Pages": ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11"],
                    "Value": "Letter",
                    "Source": "Dummy-task",
                    "TimeStamp": "2021-01-28T21:26:02.4571552Z"
                }
            ]
        },
        "UploadedBy": {
            "FirstName": "John",
            "UserName": "JD",
            "LastName": "Doe"
        },
        "UploadKey": "56tr1-231q-4af6-b12a-q213we",
        "Name": "Letter"
    }
}

**Comment by fnapolitano73** [comment]
Hi ,

so the sample file you shared has at root level a timestamp field and a nested structure containing the data:

![image](https://user-images.githubusercontent.com/51003263/152620317-19a80e4d-ccf2-44a6-8b02-eb43ec2e5e40.png)

maximum level of nested structure is 2.

The script can run in more ways:

1. fully denormalizing the json file (set the parameter --num_level_to_denormalize to a high level i.e. 999) ; in this case it   will only create one table containing all the attributes in tabular format.
![image](https://user-images.githubusercontent.com/51003263/152620542-0e330e14-ec45-480a-ab6e-582c3348abcf.png)


or 

2. keeping all the table split by the relationalize (set the parameter --num_level_to_denormalize to 0)  

![image](https://user-images.githubusercontent.com/51003263/152621210-cdcb4a09-1ef3-44bd-aa5e-a2d238903ccc.png)

and so on
or 

3. only denormalizing some levels (set the parameter --num_level_to_denormalize to the number of nested levels to collapse i.e. 1)

can you explain me what do you think get lost in the execution?

**Comment by isaac-dasari** [comment]
Option 1 worked for me.
Thanks
